name: website

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  charts_common:
dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

# flutter_web packages are not published to pub.dartlang.org
# These overrides tell the package tools to get them from GitHub

